name: Convert Postman to OpenAPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Specify the Node.js version you want to use

    - name: Install postman-to-openapi
      run: npm install @scalar/postman-to-openapi

    - name: Install js-yaml
      run: npm install js-yaml

    - name: Convert Postman to OpenAPI
      run: node convert.mjs

    - name: Upload morningstar.yml
      uses: actions/upload-artifact@v4
      with:
        name: openapi-spec
        path: morningstar.yml

  process-yaml:
    runs-on: ubuntu-latest
    needs: convert
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        repository: 'https://github.com/mathworks-ref-arch/matlab-openapi-generator.git'        

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'
     
      - name: Run Maven Package
        run: |
          ls
          cd Software/Java
          mvn clean package